name: Expert - Robot Udemy - Web

on:
  push:
    branches: [ master-udemy ]
  pull_request:
    branches: [ master-udemy ]
  workflow_dispatch:
jobs:
  job1:
    name: Setup Machine
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      # - id: step1
      #   run: echo "::set-output name=test::hello"
      # - id: step2
      #   run: echo "::set-output name=test::world"
      - name: Setup Dependencies
        run: |
            sudo apt-get install -y xvfb ca-certificates net-tools netcat gnupg ffmpeg libgtk-3-0 libgdk-pixbuf2.0-dev libxcomposite-dev libdbus-glib-1-2 libatk-bridge2.0-0 wget libgbm1 libnss3 libxss1 libasound2 
      - name: Setup Node
        run: |
          curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs
      - name: Setup python
        run: |
          python3 -m pip install --upgrade pip

  job2:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
      - name: Setup Requirements
        run: |
          pip3 install -r requirements.txt   
      - name: Run Robot Init
        run: |
          rfbrowser init
      - name: Run Robot Test
        run: |
          robot -d ./log basic/SuiteTest/Tests/
      - name: Upload a Build Artifact Logs
        uses: actions/upload-artifact@v2.2.3
        with:
          name: Robot Logs 
          path: log/